version: '3.1'

services: 
  kanban_task_pg:
    image: postgres:15.1
    container_name: kanban_task_pg
    restart: always
    environment:
      POSTGRES_DB: 'kanban_task_pg'
      POSTGRES_USER: 'udaniklean'
      POSTGRES_PASSWORD: 'secretDaniklean'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432 