image: node:alpine

stages:
  - install
  - build
  - deploy

install_dependencies:
  stage: install
  script:
    - npm install

build_application:
  stage: build
  script:
    - npm run build
  only:
    - main

deploy_application:
  stage: deploy
  script:
    - echo "Desplegando la aplicación"
    - ./ci/deploy_script.sh
  only:
    - main
